#ifndef __USER_DEF_MSG_H_
#define __USER_DEF_MSG_H_

#define	WM_LBUTTON_FIRST_DOWN WM_USER	+ 5
#define	WM_LBUTTON_NEXT_DOWN WM_USER	+ 6
#define	WM_TASK_OVER		 WM_USER	+ 7
#define	WM_XOR_HIGHLIHT		 WM_USER	+ 8
#define	WM_DELETE_CUR_ENT	 WM_USER	+ 9
#define	WM_RELEASE_STATUS	 WM_USER	+ 10
#define	WM_OBJECT_SNAPED	 WM_USER	+ 11
#define	WM_OBJECT_SELECTED	 WM_USER	+ 12
#define WM_NODE_DATA_MODIFIED WM_USER   + 13
#define WM_USER_CONFIRMED	 WM_USER    + 14
#define WM_SHIFT_APP_ENV	 WM_USER    + 15
#define WM_CMDLINE_AFFIRMED	 WM_USER    + 16
#define WM_CMDLINE_CANCELED	 WM_USER    + 17
#endif